#define F(NAME,TARGET) class NAME { \
	allowedTargets = TARGET; \
};
#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_Life

class CfgRemoteExec {
	class Functions {
		mode = 1;
		jip = 1;

		/* Client only functions RCLIENT*/
		F(SunriseClient_admin_PlayerQuery,CLIENT)
		F(SunriseClient_admin_UnitLootInfo,CLIENT)
		F(SunriseClient_admin_getID,CLIENT)
		F(SunriseClient_admin_info,CLIENT)
		F(SunriseClient_admin_sendLootToAdmin,CLIENT)
		F(SunriseClient_gangs_ClientKick,CLIENT)
		F(SunriseClient_gangs_Created,CLIENT)
		F(SunriseClient_gangs_Disbanded,CLIENT)
		F(SunriseClient_gangs_Invite,CLIENT)
		F(SunriseClient_gangs_Menu,CLIENT)
		F(SunriseClient_gangs_NewLeaderClient,CLIENT)
		F(SunriseClient_gangs_OfflineList,CLIENT)
		F(SunriseClient_garage_Menu,CLIENT)
		F(SunriseClient_garage_SellVehicleDone,CLIENT)
		F(SunriseClient_garage_SpawnVehicle,CLIENT)
		F(SunriseClient_gui_bottomNotification,CLIENT)
		F(SunriseClient_martiallaw_listWarPoints,CLIENT)
		F(SunriseClient_message_msgToTargetGetMessage,CLIENT)
		F(SunriseClient_paintball_Message,CLIENT)
		F(SunriseClient_parking_ImpoundActionDone,CLIENT)
		F(SunriseClient_parking_MenuRet,CLIENT)
		F(SunriseClient_session_banned,CLIENT)
		F(SunriseClient_session_dataQuery,CLIENT)
		F(SunriseClient_session_insertPlayerInfo,CLIENT)
		F(SunriseClient_session_nameInData,CLIENT)
		F(SunriseClient_session_requestReceived,CLIENT)
		F(SunriseClient_session_syncData,CLIENT)
		F(SunriseClient_session_updateRequest,CLIENT)
		F(SunriseClient_system_ResCaptureMenu,CLIENT)
		F(SunriseClient_system_blinded,CLIENT)
		F(SunriseClient_system_bountyReceive,CLIENT)
		F(SunriseClient_system_breathalyzer,CLIENT)
		F(SunriseClient_system_buyHouseDone,CLIENT)
		F(SunriseClient_system_copLights,CLIENT)
		F(SunriseClient_system_copMedicRequest,CLIENT)
		F(SunriseClient_system_copSearch,CLIENT)
		F(SunriseClient_system_copSearchUpdate,CLIENT)
		F(SunriseClient_system_copSiren,CLIENT)
		F(SunriseClient_system_dropAll,CLIENT)
		F(SunriseClient_system_freezePlayer,CLIENT)
		F(SunriseClient_system_getCombatVehicleDone,CLIENT)
		F(SunriseClient_system_getCombatVehicleMenu,CLIENT)
		F(SunriseClient_system_giveDiff,CLIENT)
		F(SunriseClient_system_handleInv,CLIENT)
		F(SunriseClient_system_hint,CLIENT)
		F(SunriseClient_system_healDoctor,CLIENT)
		F(SunriseClient_system_healSicknessClient,CLIENT)
		F(SunriseClient_system_houseContainer,CLIENT)
		F(SunriseClient_system_houseMenu,CLIENT)
		F(SunriseClient_system_insurancePayDone,CLIENT)
		F(SunriseClient_system_jail,CLIENT)
		F(SunriseClient_system_jailMe,CLIENT)
		F(SunriseClient_system_keyRecive,CLIENT)
		F(SunriseClient_system_knockedOut,CLIENT)
		F(SunriseClient_system_licenseCheck,CLIENT)
		F(SunriseClient_system_licensesRead,CLIENT)
		F(SunriseClient_system_lightHouse,CLIENT)
		F(SunriseClient_system_lookPassport,CLIENT)
		F(SunriseClient_system_medicLights,CLIENT)
		F(SunriseClient_system_medicMenu,CLIENT)
		F(SunriseClient_system_medicRequest,CLIENT)
		F(SunriseClient_system_medicSiren,CLIENT)
		F(SunriseClient_system_medicStatus,CLIENT)
		F(SunriseClient_system_moveIn,CLIENT)
		F(SunriseClient_system_myCash,CLIENT)
		F(SunriseClient_system_policedb,CLIENT)
		F(SunriseClient_system_punishment,CLIENT)
		F(SunriseClient_system_raidAlert,CLIENT)
		F(SunriseClient_system_receiveItem,CLIENT)
		F(SunriseClient_system_receiveMoney,CLIENT)
		F(SunriseClient_system_release,CLIENT)
		F(SunriseClient_system_removeLicenses,CLIENT)
		F(SunriseClient_system_removeItems,CLIENT)
		F(SunriseClient_system_removeWeapons,CLIENT)
		F(SunriseClient_system_removeWeaponsReward,CLIENT)
		F(SunriseClient_system_resHBClient,CLIENT)
		F(SunriseClient_system_restrain,CLIENT)
		F(SunriseClient_system_revived,CLIENT)
		F(SunriseClient_system_robPerson,CLIENT)
		F(SunriseClient_system_robReceive,CLIENT)
		F(SunriseClient_system_searchClient,CLIENT)
		F(SunriseClient_system_sellHouseDone,CLIENT)
		F(SunriseClient_system_sellSlaveAction,CLIENT)
		F(SunriseClient_system_sellSlaveDone,CLIENT)
		F(SunriseClient_system_setPlayerLicense,CLIENT)
		F(SunriseClient_system_setPlayerLvL,CLIENT)
		F(SunriseClient_system_showPassportTo,CLIENT)
		F(SunriseClient_system_smartphone,CLIENT)
		F(SunriseClient_system_soundDevice,CLIENT)
		F(SunriseClient_system_spikeStripEffect,CLIENT)
		F(SunriseClient_system_tazeSound,CLIENT)
		F(SunriseClient_system_ticketPrompt,CLIENT)
		F(SunriseClient_system_unloadFromHB,CLIENT)
		F(SunriseClient_system_vehTransferMenu,CLIENT)
		F(SunriseClient_system_vehicleActions,CLIENT)
		F(SunriseClient_system_wantedInfo,CLIENT)
		F(SunriseClient_system_wantedList,CLIENT)
		F(SunriseClient_tickets_Prompt,CLIENT)
		F(SunriseClient_vehdatabase_SearchDone,CLIENT)
		F(SunriseClient_vehicles_alarmSound,CLIENT)
		F(SunriseClient_warzones_message,CLIENT)

		/* Server only functions RSERV*/
		F(SunriseServer_database_ban,ANYONE)
		F(SunriseServer_database_insertRequest,ANYONE)
		F(SunriseServer_database_updateMoney,ANYONE)
		F(SunriseServer_database_queryRequest,ANYONE)
		F(SunriseServer_database_updatePartial,ANYONE)
		F(SunriseServer_database_updatePlayerIndCfg,ANYONE)
		F(SunriseServer_database_updateRequest,ANYONE)
		F(SunriseServer_experience_loadFromDatabase,ANYONE)
		F(SunriseServer_system_updateExp,ANYONE)
		F(SunriseServer_market_buy,ANYONE)
		F(SunriseServer_market_delete,ANYONE)
		F(SunriseServer_market_init,ANYONE)
		F(SunriseServer_market_sell,ANYONE)
		F(SunriseServer_market_takeBack,ANYONE)
		F(SunriseServer_system_JailSys,ANYONE)
		F(SunriseServer_system_addHouse,ANYONE)
		F(SunriseServer_system_addWarPoint,ANYONE)
		F(SunriseServer_system_capturePay,ANYONE)
		F(SunriseServer_system_changePlayerServerMap,ANYONE)
		F(SunriseServer_system_changeVehicleServerMap,ANYONE)
		F(SunriseServer_system_checkConnection,ANYONE)
		F(SunriseServer_system_checkHouse,ANYONE)
		F(SunriseServer_system_chopShopOwn,ANYONE)
		F(SunriseServer_system_chopShopSell,ANYONE)
		F(SunriseServer_system_cleanupMessages,ANYONE)
		F(SunriseServer_system_clientEndmission,ANYONE)
		F(SunriseServer_system_combatVehicleReq,ANYONE)
		F(SunriseServer_system_copLeaveDuty,ANYONE)
		F(SunriseServer_system_medLeaveDuty,ANYONE)
		F(SunriseServer_system_copGoOnDuty,ANYONE)
		F(SunriseServer_system_medGoOnDuty,ANYONE)
		F(SunriseServer_system_customLog,ANYONE)
		F(SunriseServer_system_endBattle,ANYONE)
		F(SunriseServer_system_getID,ANYONE)
		F(SunriseServer_system_getOffline,ANYONE)
		F(SunriseServer_system_getVehicles,ANYONE)
		F(SunriseServer_system_goMedic,ANYONE)
		F(SunriseServer_system_insertGang,ANYONE)
		F(SunriseServer_system_insurancePayRequest,ANYONE)
		F(SunriseServer_system_keyManagement,ANYONE)
		F(SunriseServer_system_kickOffline,ANYONE)
		F(SunriseServer_system_logSearch,ANYONE)
		F(SunriseServer_system_manageApplicants,ANYONE)
		F(SunriseServer_system_msgRequest,ANYONE)
		F(SunriseServer_system_newGangLeader,ANYONE)
		F(SunriseServer_system_pdatabaseDelete,ANYONE)
		F(SunriseServer_system_pdatabaseFetch,ANYONE)
		F(SunriseServer_system_pdatabaseManage,ANYONE)
		F(SunriseServer_system_rcon,ANYONE)
		F(SunriseServer_system_regAction,ANYONE)
		F(SunriseServer_system_removeGang,ANYONE)
		F(SunriseServer_system_removeWarPoint,ANYONE)
		F(SunriseServer_system_repayCredit,ANYONE)
		F(SunriseServer_system_reqCredit,ANYONE)
		F(SunriseServer_system_reqHouseInfo,ANYONE)
		F(SunriseServer_system_sellHouse,ANYONE)
		F(SunriseServer_system_serverBank,ANYONE)
		F(SunriseServer_system_serverCommand,ANYONE)
		F(SunriseServer_system_spawnVehicle,ANYONE)
		F(SunriseServer_system_spikeStrip,ANYONE)
		F(SunriseServer_system_unlockHouseContainer,ANYONE)
		F(SunriseServer_system_updateGang,ANYONE)
		F(SunriseServer_system_updateGangBank,ANYONE)
		F(SunriseServer_system_updateGangTrunks,ANYONE)
		F(SunriseServer_system_updateGangWarPoints,ANYONE)
		F(SunriseServer_system_updateHouseContainers,ANYONE)
		F(SunriseServer_system_updateHouseSlots,ANYONE)
		F(SunriseServer_system_updateHouseRent,ANYONE)
		F(SunriseServer_system_updateHouseSecurity,ANYONE)
		F(SunriseServer_system_vehSearch,ANYONE)
		F(SunriseServer_system_vehicleAdacRecolor,ANYONE)
		F(SunriseServer_system_vehicleAdacRematerial,ANYONE)
		F(SunriseServer_system_vehicleAdacUpdate,ANYONE)
		F(SunriseServer_system_vehicleCreate,ANYONE)
		F(SunriseServer_system_vehicleParkingPay,ANYONE)
		F(SunriseServer_system_vehicleParkingStore,ANYONE)
		F(SunriseServer_system_vehicleSell,ANYONE)
		F(SunriseServer_system_vehicleStore,ANYONE)
		F(SunriseServer_system_vehicleUpdate,ANYONE)
		F(SunriseServer_system_vote,ANYONE)
		F(SunriseServer_system_wantedAdd,ANYONE)
		F(SunriseServer_system_wantedBounty,ANYONE)
		F(SunriseServer_system_wantedCheck,ANYONE)
		F(SunriseServer_system_wantedFetch,ANYONE)
		F(SunriseServer_system_wantedFetchMedic,ANYONE)
		F(SunriseServer_system_wantedKilledbyCop,ANYONE)
		F(SunriseServer_system_wantedKnockedByCop,ANYONE)
		F(SunriseServer_system_wantedRemove,ANYONE)
		F(SunriseServer_system_wantedUpdateJailTime,ANYONE)
		F(SunriseServer_system_weaponShopOpen,ANYONE)
		F(SunriseServer_system_weaponShopBuy,ANYONE)
		F(SunriseServer_system_clothingShopOpen,ANYONE)
		F(SunriseServer_system_clothingShopBuy,ANYONE)
		F(SunriseServer_system_vehicleShopOpen,ANYONE)
		F(SunriseServer_system_vehicleServiceSave,ANYONE)
		F(SunriseServer_factory_order,ANYONE)
		F(SunriseServer_factory_vehicleLoad,ANYONE)
		F(SunriseServer_factory_vehicleProcess,ANYONE)
		F(SunriseServer_gasStations_startRefuel,ANYONE)
		F(SunriseServer_gasStations_finishRefuel,ANYONE)
		F(SunriseServer_gasStations_startRefuelStation,ANYONE)
		F(SunriseServer_carsharing_stop,ANYONE)
		F(SunriseServer_system_dutyGearLoad,ANYONE)
		F(SunriseServer_system_dutyGearSave,ANYONE)
		F(SunriseServer_system_becomeDispatcher,ANYONE)
		F(SunriseServer_pouch_openPouch,ANYONE)
		F(SunriseServer_pouch_updatePouch,ANYONE)
		F(SunriseServer_system_handleVehicle,ANYONE)

		/* Functions for everyone RANY*/
		F(SunriseClient_effects_Restart,ANYONE)
		F(SunriseClient_martiallaw_updateWarPoints,ANYONE)
		F(SunriseClient_system_animSync,ANYONE)
		F(SunriseClient_system_broadcast,ANYONE)
		F(SunriseClient_system_clientMessage,ANYONE)
		F(SunriseClient_system_containerActions,ANYONE)//*
		F(SunriseClient_system_demoChargeTimer,ANYONE)
		F(SunriseClient_system_flashbang,ANYONE)
		F(SunriseClient_system_lockVehicle,ANYONE)
		F(SunriseClient_system_pulloutVeh,ANYONE)
		F(SunriseClient_system_say3D,ANYONE)
		F(SunriseClient_system_setFuel,ANYONE)
		F(SunriseClient_system_setPlate,ANYONE)
		
		F(SunriseServer_ltd_regAction,SERVER)
		F(SunriseServer_ltd_updateItemShopDatabase,SERVER)
		F(SunriseServer_ltd_updateItemPrice,SERVER)
		F(SunriseServer_ltd_addItemToShopDatabase,SERVER)
		F(SunriseServer_ltd_getAllMoney,SERVER)
		
		F(BIS_fnc_holdActionAdd,ANYONE)//*
		F(BIS_fnc_deletetask,ANYONE)//*
		F(BIS_fnc_setidentity,ANYONE)
		F(BIS_fnc_settasklocal,ANYONE)//*

		/* Обязательные бисовские функции */
		F(BIS_fnc_curatorRespawn,ANYONE)
		F(BIS_fnc_effectKilledAirDestruction,ANYONE)
		F(BIS_fnc_effectKilledSecondaries,ANYONE)
		F(BIS_fnc_objectVar,ANYONE)
		F(BIS_fnc_execVM,ANYONE)

		/* */
		F(BIS_fnc_debugConsoleExec,ANYONE)
	};

	class Commands {
		mode = 1;
		jip = 1;

		F(setHitPointDamage,CLIENT)
		F(setDamage,CLIENT)
		F(setVelocity,CLIENT)

		F(diag_log,ANYONE)
		F(addAction,ANYONE)
		F(hint,ANYONE)
		F(setFace,ANYONE)
		F(setPos,ANYONE)
		F(setPosATL,ANYONE)
	};
};